################### Environment Properties ###################

# The version of Java used by your plugin. The game is built on Java 21 but
# actually runs on Java 25.
java_version=25

# Specifies the required Hytale server version for this plugin. 
# Use "*" to allow any version or a specific version string like "1.0.0".
server_version=*

# Determines if your plugin should also be loaded as an asset pack. If your
# pack contains assets, or you intend to use the in-game asset editor, you
# want this to be true.
includes_pack=true

# If true, the plugin will be installed but not activated until the user
# manually enables it in the game's plugin manager.
disabled_by_default=false

# The release channel your plugin should be built and ran against. This is
# usually release or pre-release. You can verify your settings in the
# official launcher.
patchline=release

# Determines if the development server should also load mods from the user's
# standard mods folder. This lets you test mods by installing them where a
# normal player would, instead of adding them as dependencies or adding them
# to the development server manually.
load_user_mods=false

# If Hytale was installed to a custom location, you must set the home path
# manually. You may also want to use a custom path if you are building in
# a non-standard environment like a build server. The home path should
# the folder that contains the install and UserData folder.
# hytale_home=./test-file

####################### Maven Properties ######################

# The group ID used for maven publishing. Usually the same as your package name
# but not the same as your plugin group!
maven_group=org.example

###################### Plugin Properties ######################

# The group ID used for Hytale publishing.
plugin_group=Example

# The display name of your plugin.
plugin_name=ExamplePlugin

# The main class of your plugin, used as the entry point.
plugin_main_class=org.example.plugin.ExamplePlugin

# The current version of your project. Please use semantic versioning!
plugin_version=0.0.2

# A comma-separated list of the people or teams who created the plugin.
plugin_authors=YourNameHere, OtherNameHere

# A short summary of what your plugin does, which will be visible to users.
plugin_description=An example plugin for HyTale!

# The official website or repository URL for the plugin project.
plugin_url=example.com

# A JSON object defining other plugins required for this one to function.
# Example: {"hytale.essentials": "1.0.0"}
plugin_dependencies={}

# A JSON object defining plugins that add extra features if present, 
# but are not strictly required for the plugin to run.
plugin_optional_dependencies={}