package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.player.pages.BasicCustomUIPage;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.flock.FlockMembershipSystems;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.Components.QuickAccessComponent;
import org.wojo.wojosToolbelt.Config.QuickAccessConfig;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.

public class ItemSelectionGui extends InteractiveCustomUIPage<ItemSelectionGui.UiData> {

    public static class UiData {

        private int selectedButton; // Idx of the selecetd button

        public static final BuilderCodec<UiData> CODEC = BuilderCodec.builder(UiData.class, UiData::new)
            .append(new KeyedCodec<>("ButtonIndex", Codec.INTEGER),
                (uiData,idx) -> uiData.selectedButton = idx,
                uiData -> uiData.selectedButton)
            .add()
            .build();

        public int getSelectedButton(){
            return selectedButton;
        }
    }
    
    public ItemSelectionGui(@Nonnull PlayerRef playerRef, Ref<EntityStore> ref, QuickAccessComponent playersQuickAccessComponent, Store<EntityStore> store) {
        super(playerRef, CustomPageLifetime.CanDismissOrCloseThroughInteraction, UiData.CODEC);

    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickSwap0");
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickSwap1");
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, UiData data) {
        super.handleDataEvent(ref, store, data);

        System.out.println("EVENT: " + data.toString());

        sendUpdate();
    }

    // TODO: Handle button press interaction on GUI.
}
