package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.asset.type.item.config.Item;
import com.hypixel.hytale.server.core.command.system.CommandManager;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.BasicCustomUIPage;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.flock.FlockMembershipSystems;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.Components.QuickAccessComponent;
import org.wojo.wojosToolbelt.Config.QuickAccessConfig;
import org.wojo.wojosToolbelt.QuickAccessUtils.QuickAccessUtils;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.beans.Visibility;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

public class ButtonData {
    public Message buttonMsg = null;
    public String buttonText = "N/A";

    public String buttonIcon = "";
    public String isButtonDisabled = "false";
    public String buttonStyle = "";

    public ButtonData (Message msg, String text, String icon, String is_disabled, String style){
        this.buttonMsg = msg;
        this.buttonText = text;
        this.buttonIcon = icon;
        this.isButtonDisabled = is_disabled;
        this.buttonStyle = style;
    }
}

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class ItemSelectionGui extends InteractiveCustomUIPage<ItemSelectionGui.UiData> {
    private static final GUI_FILE = "Pages/ThreeByThreeQuickAccess.ui";
    private static final String[] QUICK_SWAP_BUTTON_IDS = {
        '#QuickAccessButton1', '#QuickAccessButton2', '#QuickAccessButton3', '#QuickAccessButton4',
        '#QuickAccessButton5','#QuickAccessButton6','#QuickAccessButton7','#QuickAccessButton8'
    };

    private List<ButtonData> quickAccessButtons = new ArrayList<>(Collections.nCopies(QUICK_SWAP_BUTTON_IDS.length, new ButtonData()));
    private ButtonData settingsButton = new ButtonData();
    private ButtonData equipedItemButton = new ButtonData();
    private ItemStack associatedQuickAccessItem = null;



    public static class UiData {
        public String buttonSelected = "N/A";

        public static final BuilderCodec<UiData> CODEC = BuilderCodec.builder(UiData.class, UiData::new)
            .append(
                new KeyedCodec<>("ButtonSelected", Codec.STRING),
                (obj, val) -> obj.buttonSelected = val,
                obj -> obj.buttonSelected
            )
            .add()
            .build();
    }
    
    public ItemSelectionGui(@Nonnull PlayerRef playerRef, ItemStack quickAccessItem) {
        super(playerRef, CustomPageLifetime.CanDismissOrCloseThroughInteraction, UiData.CODEC);
        this.associatedQuickAccessItem = quickAccessItem;

        // Update Display Data with data from player and players quick access item
        //this.quickAccessButtons = this.getQuickAccessButtonData(associatedQuickAccessItem);
        //this.equipedItemButton = this.getEquippedButtonData(player, associatedQuickAccessItem);
        //this.settingsButton = this.getSettingsButtonData(associatedQuickAccessItem);
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonSettings", new EventData().append("ButtonSelected", "settings"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonEquipped", new EventData().append("ButtonSelected", "equipped"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton1", new EventData().append("ButtonSelected", "0"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton2", new EventData().append("ButtonSelected", "1"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton3", new EventData().append("ButtonSelected", "2"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton4", new EventData().append("ButtonSelected", "3"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton5", new EventData().append("ButtonSelected", "4"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton6", new EventData().append("ButtonSelected", "5"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton7", new EventData().append("ButtonSelected", "6"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton8", new EventData().append("ButtonSelected", "7"), true);


        uiCommandBuilder.append(GUI_FILE);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButtonSettings.Text", this.settingsButton);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButtonEquipped.Text", this.equipedItemButton);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton0.Text", this.quickAccessButtons[0]);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton1.Text", this.quickAccessButtons[1]);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton2.Text", this.quickAccessButtons[2]);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton3.Text", this.quickAccessButtons[3]);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton4.Text", this.quickAccessButtons[4]);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton5.Text", this.quickAccessButtons[5]);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton6.Text", this.quickAccessButtons[6]);
        this.setButtonText(uiCommandBuilder, "#QuickAccessButton7.Text", this.quickAccessButtons[7]);


    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, UiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Output Data! "+data.buttonSelected);
        String buttonPressed = data.buttonSelected;

        if (buttonPressed.equals("N/A")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("N/A");
        } else if (buttonPressed.equals("settings")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("Settings Pressed");
        } else if (buttonPressed.equals("equipped")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("Equipped Pressed");
        } else if (buttonPressed.equals("toggle")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("Toggle Pressed");
        } else{
                CommandManager.get().handleCommand(playerRef, "swap --src-pos "+buttonPressed);
        }
        this.close();
    }

    private setButtonText(UICommandBuilder builder, String key, ButtonData data) {
        if (data.buttonMsg != null){
            builder.set(key, data.buttonMsg);
        }else{
            builder.set(key, data.buttonText);
        }
    }

    private ButtonData getQuickAccessButtonData(ItemStack quick_access_item){

    }

    private ButtonData getEquippedButtonData(Player player, ItemStack quick_access_item){

        // msg, text, icon, isDisabled, stlye
        QuickAccessUtils.;
        return new ButtonData(null, "", "Icon", "false", "style")
    }

    private ButtonData getSettingsButtonData(ItemStack quickAccessItem){
        // msg, text, icon, isDisabled, stlye
        return new ButtonData(null, "!Settings!", "Icon", "false", "style")
    }
}
