package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.command.system.CommandManager;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.BasicCustomUIPage;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.flock.FlockMembershipSystems;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.Components.QuickAccessComponent;
import org.wojo.wojosToolbelt.Config.QuickAccessConfig;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.beans.Visibility;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class ItemSelectionGui extends InteractiveCustomUIPage<ItemSelectionGui.UiData> {
    String[] buttonNames = new String[10];
    Boolean[] isButtonDisabled = new Boolean[10];
    String equippedItem = "Empty";

    public static class UiData {
        public String buttonSelected = "N/A";

        public static final BuilderCodec<UiData> CODEC = BuilderCodec.builder(UiData.class, UiData::new)
            .append(
                new KeyedCodec<>("ButtonSelected", Codec.STRING),
                (obj, val) -> obj.buttonSelected = val,
                obj -> obj.buttonSelected
            )
            .add()
            .build();
    }
    
    public ItemSelectionGui(@Nonnull PlayerRef playerRef, String equippedItem, String[] storedItems, Boolean[] disabledButtons) {
        super(playerRef, CustomPageLifetime.CanDismissOrCloseThroughInteraction, UiData.CODEC);
        this.equippedItem = equippedItem;
        this.buttonNames = storedItems.clone();
        this.isButtonDisabled = disabledButtons.clone();
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonSettings", new EventData().append("ButtonSelected", "settings"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonEquipped", new EventData().append("ButtonSelected", "equipped"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton1", new EventData().append("ButtonSelected", "0"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton2", new EventData().append("ButtonSelected", "1"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton3", new EventData().append("ButtonSelected", "2"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton4", new EventData().append("ButtonSelected", "3"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton5", new EventData().append("ButtonSelected", "4"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton6", new EventData().append("ButtonSelected", "5"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton7", new EventData().append("ButtonSelected", "6"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton8", new EventData().append("ButtonSelected", "7"), true);

        uiCommandBuilder.append("Pages/ThreeByThreeQuickAccess.ui");
        uiCommandBuilder.set("#QuickAccessButtonEquipped.Text", equippedItem);
        uiCommandBuilder.set("#QuickAccessButton1.Text", buttonNames[0]);
        uiCommandBuilder.set("#QuickAccessButton2.Text", buttonNames[1]);
        uiCommandBuilder.set("#QuickAccessButton3.Text", buttonNames[2]);
        uiCommandBuilder.set("#QuickAccessButton4.Text", buttonNames[3]);
        uiCommandBuilder.set("#QuickAccessButton5.Text", buttonNames[4]);
        uiCommandBuilder.set("#QuickAccessButton6.Text", buttonNames[5]);
        uiCommandBuilder.set("#QuickAccessButton7.Text", buttonNames[6]);
        uiCommandBuilder.set("#QuickAccessButton8.Text", buttonNames[7]);

        uiCommandBuilder.set("#QuickAccessButton1.Disabled", isButtonDisabled[0].toString());
        uiCommandBuilder.set("#QuickAccessButton2.Disabled", isButtonDisabled[1].toString());
        uiCommandBuilder.set("#QuickAccessButton3.Disabled", isButtonDisabled[2].toString());
        uiCommandBuilder.set("#QuickAccessButton4.Disabled", isButtonDisabled[3].toString());
        uiCommandBuilder.set("#QuickAccessButton5.Disabled", isButtonDisabled[4].toString());
        uiCommandBuilder.set("#QuickAccessButton6.Disabled", isButtonDisabled[5].toString());
        uiCommandBuilder.set("#QuickAccessButton7.Disabled", isButtonDisabled[6].toString());
        uiCommandBuilder.set("#QuickAccessButton8.Disabled", isButtonDisabled[7].toString());



        //uiCommandBuilder.set("#QuickSwap1.Visible", false);
        // TODO: Set Button bg to item icon?

    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, UiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Output Data! "+data.buttonSelected);
        String buttonPressed = data.buttonSelected;

        if (buttonPressed.equals("N/A")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("N/A");
        } else if (buttonPressed.equals("settings")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("Settings Pressed");
        } else if (buttonPressed.equals("equipped")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("Equipped Pressed");
        } else{
                CommandManager.get().handleCommand(playerRef, "swap --src-pos "+buttonPressed);
        }
        this.close();
    }
}
