package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.asset.type.item.config.Item;
import com.hypixel.hytale.server.core.command.system.CommandManager;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.BasicCustomUIPage;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.flock.FlockMembershipSystems;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.Components.QuickAccessComponent;
import org.wojo.wojosToolbelt.Config.QuickAccessConfig;
import org.wojo.wojosToolbelt.QuickAccessUtils.QuickAccessUtils;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.beans.Visibility;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class PlayerSettingsGui extends InteractiveCustomUIPage<PlayerSettingsGui.SettingsUiData> {
    // ============ UI DATA ============
    public static class SettingsUiData {
        public Boolean _isEnabled = false;
        public Integer _equippedPos = 8;
        public Integer _targetPos = 0;
    
        public ButtonData (Boolean is_enabled, Integer equipped_pos, Integer target_pos) {
            this._isEnabled = is_enabled;
            this._equippedPos = equipped_pos;
            this._targetPos = target_pos;
        }
    
        public static final BuilderCodec<SettingsUiData> CODEC = BuilderCodec.builder(SettingsUiData.class, SettingsUiData::new)
            .append(
                new KeyedCodec<>("IsEnabled", Codec.BOOLEAN),
                (obj, val) -> obj._isEnabled = val,
                obj -> obj._isEnabled
            )
            .add()
            .append(
                new KeyedCodec<>("EquippedPos", Codec.INTEGER),
                (obj, val) -> obj._equippedPos = val,
                obj -> obj._equippedPos
            )
            .add()
            .append(
                new KeyedCodec<>("TargetPos", Codec.INTEGER),
                (obj, val) -> obj._targetPos = val,
                obj -> obj._targetPos
            )
            .add()
            .build();
    }
    // ------------ END UI DATA ------------
  
    private static final GUI_FILE = "Pages/QuickAccessSettings.ui";

    
    public PlayerSettingsGui(@Nonnull PlayerRef player_ref, Player player) {
        super(player_ref, CustomPageLifetime.CanDismissOrCloseThroughInteraction, SettingsUiData.CODEC);
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, 
                      @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiCommandBuilder.append(GUI_FILE);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, SettingsUiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Output Data! "+data.buttonSelected);
        this.close();
    }
}
