package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class PlayerSettingsGui extends InteractiveCustomUIPage<PlayerSettingsGui.SettingsUiData> {
    // ------ UI Interaction Data ------
    public static class SettingsUiData {
        public Boolean isEnabled = false;
        public Integer equippedPos = 8;
        public Integer targetPos = 0;
        public String guiFile = "";
    
        public SettingsUiData (Boolean is_enabled, Integer equipped_pos, Integer target_pos, String gui_file) {
            this.isEnabled = is_enabled;
            this.equippedPos = equipped_pos;
            this.targetPos = target_pos;
            this.guiFile = gui_file;
        }

        public SettingsUiData(){
        }

        public static final BuilderCodec<SettingsUiData> CODEC = BuilderCodec.builder(SettingsUiData.class, SettingsUiData::new)
            .append(
                new KeyedCodec<>("IsEnabled", Codec.BOOLEAN),
                (obj, val) -> obj.isEnabled = val,
                obj -> obj.isEnabled
            )
            .add()
            .append(
                new KeyedCodec<>("EquippedPos", Codec.INTEGER),
                (obj, val) -> obj.equippedPos = val,
                obj -> obj.equippedPos
            )
            .add()
            .append(
                new KeyedCodec<>("TargetPos", Codec.INTEGER),
                (obj, val) -> obj.targetPos = val,
                obj -> obj.targetPos
            )
            .add()
            .append(
                new KeyedCodec<>("GuiFile", Codec.STRING),
                (obj, val) -> obj.guiFile = val,
                obj -> obj.guiFile
            )
            .add()
            .build();
    }
    // ------------ END UI DATA ------------
  
    public static final String SETTINGS_GUI_FILE = "Pages/QuickAccessSettings.ui";

    
    public PlayerSettingsGui(@Nonnull PlayerRef player_ref, Player player) {
        super(player_ref, CustomPageLifetime.CanDismissOrCloseThroughInteraction, SettingsUiData.CODEC);
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, 
                      @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiCommandBuilder.append(SETTINGS_GUI_FILE);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, SettingsUiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Output Data:\n "+data+"------\n\n");
        this.close();
    }
}
