package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.Components.QuickAccessPlayerComponent;
import org.wojo.wojosToolbelt.Config.QuickAccessConfig;
import org.wojo.wojosToolbelt.QuickAccessUtils.QuickAccessUtils;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class PlayerSettingsGui extends InteractiveCustomUIPage<PlayerSettingsGui.SettingsUiData> {
    // ------ UI Interaction Data ------
    public static class SettingsUiData {
        public Boolean isEnabled = false;
        public Integer equippedPos = 8;
        public Integer targetPos = 0;
        public String guiFile = QuickAccessConfig.SELECTION_GUI_FILE_GRID_THREE_BY_THREE;
        public String buttonSelected = "";

        public String getDebugString(){
            return String.format("------ SettingsUiData ------\n - IsEnabled: %b\n - equippedPos: %d\n - targetPos: %d\n - guiFile: %s\n - buttonSelected: %s",
                this.isEnabled,
                this.equippedPos,
                this.targetPos,
                this.guiFile,
                this.buttonSelected
            );
        }

        public void update(SettingsUiData data){
            this.isEnabled = data.isEnabled;
            this.equippedPos = data.equippedPos;
            this.targetPos = data.targetPos;
            this.guiFile = data.guiFile;
            this.buttonSelected = data.buttonSelected;
        };

        public SettingsUiData(){
        }

        public static final BuilderCodec<SettingsUiData> CODEC = BuilderCodec.builder(SettingsUiData.class, SettingsUiData::new)
            .append(
                new KeyedCodec<>("@IsEnabledCheckbox", Codec.BOOLEAN),
                (obj, val) -> obj.isEnabled = val,
                obj -> obj.isEnabled
            )
            .add()
            .append(
                new KeyedCodec<>("@EquippedNumberField", Codec.INTEGER),
                (obj, val) -> obj.equippedPos = val,
                obj -> obj.equippedPos
            )
            .add()
            .append(
                new KeyedCodec<>("@TargetNumberField", Codec.INTEGER),
                (obj, val) -> obj.targetPos = val,
                obj -> obj.targetPos
            )
            .add()
            .append(
                new KeyedCodec<>("@GuiFileTextField", Codec.STRING),
                (obj, val) -> obj.guiFile = val,
                obj -> obj.guiFile
            )
            .add()
            .append(
                new KeyedCodec<>("ButtonSelected", Codec.STRING),
                (obj, val) -> obj.buttonSelected = val,
                obj -> obj.buttonSelected
            )
            .add()
            .build();
    }

    // ------------ END UI DATA ------------
    SettingsUiData _uiData = new SettingsUiData();

    
    public PlayerSettingsGui(@Nonnull PlayerRef player_ref, Store<EntityStore> store) {
        super(player_ref, CustomPageLifetime.CanDismissOrCloseThroughInteraction, SettingsUiData.CODEC);

        QuickAccessPlayerComponent qaPlayerComp = store.getComponent(player_ref.getReference(), QuickAccessPlayerComponent.getComponentType());
        if (qaPlayerComp != null){
            this._uiData.isEnabled = qaPlayerComp.getIsEnabled();
            this._uiData.equippedPos = qaPlayerComp.getEquippedPosition();
            this._uiData.targetPos = qaPlayerComp.getTargetPosition();
            this._uiData.guiFile = qaPlayerComp.getGuiFile();
        }
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, 
                      @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiEventBuilder.addEventBinding(
            CustomUIEventBindingType.ValueChanged, "#IsEnabledCheckbox #CheckBox",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","IsEnabledCheckbox"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.ValueChanged, "#EquippedNumberField",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","EquippedNumberField"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.ValueChanged, "#TargetNumberField",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","TargetNumberField"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.ValueChanged, "#GuiFileTextField",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","GuiFileTextField"), false
        );

        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#TwoByTwoUiButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","TwoByTwo"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#ThreeByThreeUiButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","ThreeByThree"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#FourByFourUiButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","FourByFour"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#FiveByFiveUiButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","FiveByFive"), false
        );

        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#ResetButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","ResetButton"), false
        );
        uiEventBuilder.addEventBinding(
                CustomUIEventBindingType.Activating, "#SubmitButton",
                EventData.of("@IsEnabledCheckbox", "#IsEnabledCheckbox #CheckBox.Value")
                        .append("@EquippedNumberField", "#EquippedNumberField.Value")
                        .append("@TargetNumberField","#TargetNumberField.Value")
                        .append("@GuiFileTextField","#GuiFileTextField.Value")
                        .append("ButtonSelected","SubmitButton"), false
        );

        uiCommandBuilder.append(QuickAccessConfig.SETTINGS_GUI_FILE);

        uiCommandBuilder.set("#IsEnabledCheckbox #CheckBox.Value", _uiData.isEnabled);
        uiCommandBuilder.set("#EquippedNumberField.Value", _uiData.equippedPos);
        uiCommandBuilder.set("#TargetNumberField.Value", _uiData.targetPos);
        uiCommandBuilder.set("#GuiFileTextField.Value", _uiData.guiFile);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @NonNullDecl SettingsUiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Output Settings Data:\n "+data.getDebugString()+"\n\n");
        if (data.buttonSelected.contains("SubmitButton")){
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: PlayerSettingsGui - SUBMIT new settings values to player with data\n"+data.getDebugString());

            QuickAccessPlayerComponent newPlayerComp = new QuickAccessPlayerComponent();
            newPlayerComp.setIsEnabled(this._uiData.isEnabled);
            newPlayerComp.setTargetPosition(this._uiData.targetPos);
            newPlayerComp.setEquippedPosition(this._uiData.equippedPos);
            newPlayerComp.setGuiFile(this._uiData.guiFile);

            newPlayerComp = QuickAccessUtils.validateQuickAccessPlayerComponent(newPlayerComp);
            store.replaceComponent(ref, QuickAccessPlayerComponent.getComponentType(), newPlayerComp);
            this.close();
        }else if (data.buttonSelected.contains("ResetButton")) {
            data = new SettingsUiData();
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: PlayerSettingsGui - Reset settings values\n");
        }else if (data.buttonSelected.contains("TwoByTwo")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_GRID_TWO_BY_TWO;
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: PlayerSettingsGui - Update Gui File to TwoByTwo\n");
        }else if (data.buttonSelected.contains("ThreeByThree")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_GRID_THREE_BY_THREE;
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: PlayerSettingsGui - Update Gui File to ThreeByThree\n");
        }else if (data.buttonSelected.contains("FourByFour")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_GRID_FOUR_BY_FOUR;
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: PlayerSettingsGui - Update Gui File to FourByFour\n");
        }else if (data.buttonSelected.contains("FiveByFive")) {
            data.guiFile = QuickAccessConfig.SELECTION_GUI_FILE_GRID_FIVE_BY_FIVE;
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: PlayerSettingsGui - Update Gui File to FiveByFive\n");
        }

        this._uiData.update(data);
        this.rebuild();
    }
}
