package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.asset.type.item.config.Item;
import com.hypixel.hytale.server.core.command.system.CommandManager;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.inventory.InventoryComponent;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import org.checkerframework.checker.nullness.compatqual.NonNullDecl;
import org.wojo.wojosToolbelt.Components.QuickAccessItemComponentFactory;
import org.wojo.wojosToolbelt.Components.QuickAccessPlayerComponent;
import org.wojo.wojosToolbelt.Config.QuickAccessConfig;
import org.wojo.wojosToolbelt.Events.SwapQuickAccessItemEvent;
import org.wojo.wojosToolbelt.QuickAccessUtils.*;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.util.*;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
//
public class SelectionUiThreeByThree extends InteractiveCustomUIPage<ItemSelectionGui.SelectionUiData> {
    // ------ Display data ------
    public static class ButtonData {
        public Message buttonMsg = null;
        public String buttonText = "";

        public String buttonIcon = "";
        public String isButtonDisabled = "false";
        public String buttonStyle = "";
        public String uiId = "";
        public String buttonType = "Default"; // ItemSlot, Default

        public ButtonData (Message msg, String icon, String is_disabled, String style){
            this.buttonMsg = msg;
            this.buttonIcon = icon;
            this.isButtonDisabled = is_disabled;
            this.buttonStyle = style;
        }

        public String getDebugString() {
            String output = "-----------\n[DEBUG] ButtonData: \n";
            if (buttonMsg != null){
                output += (" - msg: "+buttonMsg.getRawText())+"\n";
            }else{
                output += " - msg: null\n";
            }

            output += " - text: "+buttonText+"\n";
            output += " - icon: "+buttonIcon+"\n";
            output += " - isDis: "+isButtonDisabled+"\n";
            output += " - style: "+buttonStyle+"\n";
            return output;
        }
    }

    // NOTE: 3x3 Display has Folloiwng:
    // - 8 Selectable items
    // - 1 Equipped Item
    // - Status Button, Settings Button, Help Button
    // See: resources/Common/UI/Custom/Pages/Radials/ThreeByThreeQuickAccess.ui
    private final Integer _NUM_QA_BUTTONS = 8;
    private String _guiFile = QuickAccessConfig.SELECTION_GUI_FILE_THREE_BY_THREE;
    private ButtonData _quickAccessButton0 = new ButtonData(null,"","","true");
    private ButtonData _quickAccessButton1 = new ButtonData(null,"","","true");
    private ButtonData _quickAccessButton2 = new ButtonData(null,"","","true");
    private ButtonData _quickAccessButton3 = new ButtonData(null,"","","true");
    private ButtonData _quickAccessButton4 = new ButtonData(null,"","","true");
    private ButtonData _quickAccessButton5 = new ButtonData(null,"","","true");
    private ButtonData _quickAccessButton6 = new ButtonData(null,"","","true");
    private ButtonData _quickAccessButton7 = new ButtonData(null,"","","true");
  
    private ButtonData _statusButton = new ButtonData(null,"","","true");
    private ButtonData _helpButton = new ButtonData(null,"","","true");
    private ButtonData _settingsButton = new ButtonData(null,"","","true");
    private ButtonData _equipedItemButton =  new ButtonData(null,"","","true");
  
    private boolean _isQuickAccessItemHeld = false;
    private Integer _quickAccessItemHotbarPosition = 8;
    private QuickAccessPlayerComponent _playerQaComp = null; // Player Specific Quick Access Settings
    private ItemStack _quickAccessItem = null;               // The Quick Access Item the user is interacting with
    private ItemStack _targetItem = null;                    // Whats in the location swap will be placed in
  
    // ------ UI Interaction Data ------
    public static class SelectionUiData {
        public String buttonSelected = "N/A";

        public static final BuilderCodec<SelectionUiData> CODEC = BuilderCodec.builder(SelectionUiData.class, SelectionUiData::new)
                .append(
                        new KeyedCodec<>("ButtonSelected", Codec.STRING),
                        (obj, val) -> obj.buttonSelected = val,
                        obj -> obj.buttonSelected
                )
                .add()
                .build();
    }

    private void loadEquippedButtonData(ItemStack target_item) {
        this._equipedItemButton.isButtonDisabled = "false";
        this._equipedItemButton.buttonIcon = "";
        this._equipedItemButton.buttonStyle = "";

        if (target_item != null){
            WojosQuickAccessPlugin.LOGGER.atInfo().log("Equipped item is not null! Its: "+target_item.getItemId());
            try {
                String translatedName = Item.getAssetMap().getAsset(target_item.getItemId()).getTranslationKey();
                this._equipedItemButton.buttonMsg = Message.translation(translatedName);
            } catch (Exception e) {
                this._equipedItemButton.buttonText = target_item.getItemId();
            }
        }else{
            this._equipedItemButton.buttonText = "------";
        }
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Loaded equipped btn info");
    }

    private void loadSettingsAndHelpButtonData() {
        this._settingsButton.buttonText = "Settings";
        this._settingsButton.buttonIcon = "";
        this._settingsButton.isButtonDisabled = "false";
        

        this._helpButton.buttonText = "Help";
        this._helpButton.buttonIcon = "";
        this._helpButton.isButtonDisabled = "false";
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Loaded settings & help btn info");
    }

    public ItemSelectionGui(@Nonnull PlayerRef player_ref, Store<EntityStore> store, Boolean is_item_held) {
        super(player_ref, CustomPageLifetime.CanDismissOrCloseThroughInteraction, SelectionUiData.CODEC);
        
        // Save data needed for display (QuickAccessItem Data, QuickAccessPlayerData, Player Event Data)
        WojosQuickAccessPlugin.LOGGER.atInfo().log("[Debug] Is item held: "+String.valueOf(is_item_held));
        this._isQuickAccessItemHeld = is_item_held;
        this._playerQaComp = store.getComponent(player_ref.getReference(), QuickAccessPlayerComponent.getComponentType());
      
        Player player = store.getComponent(player_ref.getReference(), Player.getComponentType());
        InventoryComponent.Hotbar hotbar = (InventoryComponent.Hotbar) store.getComponent(player_ref.getReference(), InventoryComponent.getComponentTypeById(InventoryComponent.HOTBAR_SECTION_ID));

        // Try to get QuickAccessItem by pulling ItemStack from hotbars active slot or QuickAccess Configs equipped slot 
        if (this._isQuickAccessItemHeld){
            this._quickAccessItem = QuickAccessUtils.getHeldQaItemOrNull(player_ref, store);
            this._quickAccessItemHotbarPosition = (int) hotbar.getActiveSlot();
        }else{
            this._quickAccessItemHotbarPosition = _playerQaComp.getEquippedPosition();
            this._quickAccessItem = QuickAccessUtils.getEquippedQaItemOrNull(player_ref, store);
        }

        this._targetItem = QuickAccessUtils.getEquippedTargetItemOrNull(player_ref, store);

        // ------ Error Handling ------
        if ( this._quickAccessItem == null ) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[Error] No Quick Access Item Held or Equipped!");
        }
        if ( this._playerQaComp == null ) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[Error] Player does not have a Quick Access component!");
        }
        if ( this._targetItem == null ) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[Warn] Player does not have an item in the target location!");
        }
        // ----------------------------- End Data Collection -----------------------------
        // ===============================================================================
        
        // ------ Set Selection button Data ------

        // ------ Set Equipped Button Data ------

        // ------ Set Non Icon Button Data ------
        // Help, Settings, Status
        
        

        // ----------------------------- End Button Configs -----------------------------
        // ==============================================================================

        // Output Used QuickAccess Item information
        WojosQuickAccessPlugin.LOGGER.atInfo().log("\n\n------ Item Stack Data ------\n"+this._quickAccessItem.toString());
        WojosQuickAccessPlugin.LOGGER.atInfo().log("\n------ Quick Access Item Component ------\n"+ QuickAccessItemComponentFactory.createQuickAccessItemComponent(this._quickAccessItem).getPrintableString());

        // ----------------------------- End Debug Output -----------------------------
        // ============================================================================
    }

    private void setItemData(UICommandBuilder command_builder, String button_id, ButtonData button_data){
        if (button_data.buttonIcon) {
        
        } else {
        
        }

        if (button_data.buttonText) {
        
        } else {
          
        }
      
        if (button_id.equals("#QuickAccessButtonEquipped")){
            command_builder.set("#QuickAccessButtonEquippedImg.ItemId", "Quick_Access_Item_Common_Unrestricted");
        }else {
            if (button_data.buttonMsg != null) {
                command_builder.set(button_id + ".Text", button_data.buttonMsg);
            } else {
                command_builder.set(button_id + ".Text", button_data.buttonText);
            }
            boolean isDiabled = true;
            if ("false".equals(button_data.isButtonDisabled)) {
                isDiabled = false;
            }
            command_builder.set(button_id + ".Disabled", isDiabled);
        }
    }

    @Override
    public void build(@NonNullDecl Ref<EntityStore> ref, @NonNullDecl UICommandBuilder uiCommandBuilder, @NonNullDecl UIEventBuilder uiEventBuilder, @NonNullDecl Store<EntityStore> store) {
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton7", new EventData().append("ButtonSelected", "7"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton6", new EventData().append("ButtonSelected", "6"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton5", new EventData().append("ButtonSelected", "5"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton4", new EventData().append("ButtonSelected", "4"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton3", new EventData().append("ButtonSelected", "3"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton2", new EventData().append("ButtonSelected", "2"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton1", new EventData().append("ButtonSelected", "1"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButton0", new EventData().append("ButtonSelected", "0"), true);

        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonHelp", new EventData().append("ButtonSelected", "help"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonEquipped", new EventData().append("ButtonSelected", "equipped"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonStatus", new EventData().append("ButtonSelected", "status"), true);
        uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#QuickAccessButtonSettings", new EventData().append("ButtonSelected", "settings"), true);
      
        uiCommandBuilder.append(this._guiFile);

        setItemData(uiCommandBuilder, "#QuickAccessButton0", this._quickAccessButton0);
        setItemData(uiCommandBuilder, "#QuickAccessButton1", this._quickAccessButton1);
        setItemData(uiCommandBuilder, "#QuickAccessButton2", this._quickAccessButton2);
        setItemData(uiCommandBuilder, "#QuickAccessButton3", this._quickAccessButton3);
        setItemData(uiCommandBuilder, "#QuickAccessButton4", this._quickAccessButton4);
        setItemData(uiCommandBuilder, "#QuickAccessButton5", this._quickAccessButton5);
        setItemData(uiCommandBuilder, "#QuickAccessButton6", this._quickAccessButton6);
        setItemData(uiCommandBuilder, "#QuickAccessButton7", this._quickAccessButton7);
      
        setItemData(uiCommandBuilder, "#QuickAccessButtonEquipped", this._equipedItemButton);
        setItemData(uiCommandBuilder, "#QuickAccessButtonSettings", this._settingsButton);
        setItemData(uiCommandBuilder, "#QuickAccessButtonEquipped", this._statusButton);
        setItemData(uiCommandBuilder, "#QuickAccessButtonHelp", this._helpButton);
    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @NonNullDecl SelectionUiData data) {
        super.handleDataEvent(ref, store, data);
        WojosQuickAccessPlugin.LOGGER.atInfo().log("Output Data! "+data.buttonSelected);
        String buttonPressed = data.buttonSelected;

        if (buttonPressed.equals("N/A")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("N/A");
            this.close();
        } else if (buttonPressed.equals("settings")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Settings Pressed");
            PlayerSettingsGui guiPage = new PlayerSettingsGui(playerRef, store);
            Player player = store.getComponent(ref, Player.getComponentType());
            player.getPageManager().openCustomPage(ref, store, guiPage);
        } else if (buttonPressed.equals("status") {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Status Pressed");
            PlayerSettingsGui guiPage = new PlayerSettingsGui(playerRef, store);
            Player player = store.getComponent(ref, Player.getComponentType());
            player.getPageManager().openCustomPage(ref, store, guiPage);
        } else if (buttonPressed.equals("equipped")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Equipped Pressed");
            this.close();
        } else if (buttonPressed.equals("help")) {
            WojosQuickAccessPlugin.LOGGER.atInfo().log("[DEBUG]: Help Pressed");
            this.close();
        } else{
            this.close();
            short containerPos = Short.parseShort(buttonPressed);
            short equippedPos = _quickAccessItemHotbarPosition.shortValue();
            short targetPos = (short)_playerQaComp.getTargetPosition();
            SwapQuickAccessItemEvent.dispatch(playerRef.getReference(), store, containerPos, equippedPos, targetPos);
        }
    }

}
