package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.player.pages.BasicCustomUIPage;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.flock.FlockMembershipSystems;
import org.wojo.wojosToolbelt.Components.QuickAccessComponent;
import org.wojo.wojosToolbelt.WojosQuickAccessPlugin;

import javax.annotation.Nonnull;
import java.util.ArrayList;
import java.util.List;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.

public class ToolSelectionGui extends BasicCustomUIPage {

    private class ItemDisplayData {
        int entityListId = 0; // Position in QuickAccessComponent::_items_in_quick_access list
        String itemName = "";
        String itemIconPath = "";
        boolean isDisplayed = false;
    }
    
    private List<ItemDisplayData> _display_data;
    private int _num_displayed_items = 0;
    
    public ToolSelectionGui(@Nonnull PlayerRef playerRef) {
        super(playerRef, CustomPageLifetime.CanDismissOrCloseThroughInteraction);

        Ref<EntityStore> ref = playerRef.getReference();



        if(ref != null){
            Store<EntityStore> store = ref.getStore();

            QuickAccessComponent _qa_comp = store.getComponent(ref, QuickAccessComponent.getComponentType());

            // TODO: Build DisplayData from comp
            //
        }
    }

    @Override
    public void build(@Nonnull UICommandBuilder uiCommandBuilder) {
        // Path is relative to:
        //      src/main/resources/Common/UI/Custom
        uiCommandBuilder.append("Pages/ToolSelectionUI.ui");
        // TODO: Load different displays bassed on number of components?
    }

    // TODO: Handle button press interaction on GUI.
}
