package org.wojo.wojosToolbelt.ui;

import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.entity.entities.player.pages.BasicCustomUIPage;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.

public class ToolSelectionGui extends BasicCustomUIPage {

    public ToolSelectionGui(@Nonnull PlayerRef playerRef) {
        super(playerRef, CustomPageLifetime.CanDismissOrCloseThroughInteraction);
    }

    @Override
    public void build(@Nonnull UICommandBuilder uiCommandBuilder) {
        // Path is relative to:
        //      src/main/resources/Common/UI/Custom
       uiCommandBuilder.append("Pages/ToolSelectionUI.ui");
    }
}
